#ifndef BOARD_BUTTONSCONTROLLER_CONFIG_H
#define BOARD_BUTTONSCONTROLLER_CONFIG_H

#define BUTTONSCONTROLLER_EXCLUDE_FROM_BUILD        0       /* Default: 0 */
#define TRACE_BUTTONSCONTROLLER_NOTIFICATIONS       0

typedef enum ButtonName {
    B_CALL_ON_FLOOR_1 = 0,
    B_CALL_ON_FLOOR_2 = 1,
    B_ELEVATOR_UP     = 2,
    B_ELEVATOR_DOWN   = 3
} ButtonName;

#endif // BOARD_BUTTONSCONTROLLER_CONFIG_H
