#ifndef SECURITY_CONFIG_H
#define SECURITY_CONFIG_H

typedef enum IssueNumber {
    UNKNOWN_ISSUE = 0,
    ISSUE_MAXIMUM_LIFT_EXCEEDED = 1,
    ISSUE_MOTOR_NO_MORE_SPINNING,

    ISSUE_LIMIT_SWITCH_MULTIPLE_ACTIVE,
    ISSUE_LIMIT_SWITCH_ACTIVE_WHILE_MOVING,
    ISSUE_LIMIT_SWITCH_NONE_ACTIVE_AT_STOP,
    ISSUE_LIMIT_SWITCH_WRONG_AT_STOP
} IssueNumber;

#endif // SECURITY_CONFIG_H
